### ISSUE TITLE
callback url is wrong

### ISSUE THREAD

**Issue by gl2748** [steemit/example-steemconnect-angular#11]
Currently:
https://github.com/steemit/example-steemconnect-angular/blob/master/app.js#L3
```
callbackURL: 'https://steemit.github.io/sc2-angular'
```
Should be:
```
callbackURL: 'https://steemit.github.io/example-steemconnect-angular'
```

**Comment by bonustrack** [comment]
Good catch @gl2748 . We've fixed it, redirection is working fine now.
