### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by jcrubino** [steemit/example-steemconnect-angular#7]
1. The Demo is not working.
2. The Demo should give a confirmation or error with remediation steps after user login attempt
3. The Demo goes to a github error page.

**Comment by NicolasPerl** [comment]
Hi @jcrubino,

The demo is working properly. If you look at the authorized apps within your steemconnect account you will notice 'busy.app' should already be authorized. The reason it is bringing up a GitHub 404 page is that the callbackurl is pointing to a GitHub link that is not found. 

If you revoke the tokens on your SteemConnect dashboard for busy.app and try the demo again you will see the logic works properly.

I hope this helps!

**Comment by jcrubino** [comment]
Thanks!
